### ISSUE TITLE
Cannot find module 'resolve'

### ISSUE THREAD

**Issue by Sookhee** [Sookhee/React-study-withMirim#1]
D:\react-withMirim\styling-react>yarn start
yarn run v1.19.1
$ node scripts/start.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'resolve'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\react-withMirim\styling-react\config\webpack.config.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Sookhee** [comment]
yarn add --dev babel-jest @babel/core @babel/preset-env
